# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_event(self):
    self.driver.get("https://www.eventcreate.com/users/sign_in")
    self.driver.set_window_size(1060, 806)
    self.driver.find_element(By.ID, "user_email").send_keys("akramtest568@gmail.com")
    self.driver.find_element(By.ID, "user_password").send_keys("Akram123!")
    self.driver.find_element(By.ID, "user_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Create New Event").click()
    self.driver.find_element(By.LINK_TEXT, "Continue with Offset").click()
    self.driver.find_element(By.ID, "event_name").click()
    self.driver.find_element(By.ID, "event_name").send_keys("My Birthday")
    element = self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(8)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(8)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(8)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "new_event").click()
    dropdown = self.driver.find_element(By.ID, "event_event_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Professional']").click()
    self.driver.find_element(By.ID, "event_event_type").click()
    dropdown = self.driver.find_element(By.ID, "event_event_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Birthday']").click()
    self.driver.find_element(By.ID, "event_date_start").click()
    self.driver.find_element(By.LINK_TEXT, "12").click()
    self.driver.find_element(By.LINK_TEXT, "Add End Date/Time").click()
    self.driver.find_element(By.ID, "event_time_end").click()
    self.driver.find_element(By.CSS_SELECTOR, ".paid-select .col-md-4:nth-child(2) .form-enhanced").click()
    self.driver.find_element(By.ID, "createnow").click()
    self.driver.find_element(By.ID, "showtooltip").click()
    self.driver.find_element(By.LINK_TEXT, "Events").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pull-right:nth-child(2) .dropdown-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
